### ISSUE TITLE
improve docs 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ide-stories/vscode-stories#30]

**Comment by kirtirajsinh** [comment]
What should be improved?

**Comment by matronator** [comment]
> What should be improved?

Everything

**Comment by benawad** [comment]
PR's welcome :)

**Comment by DGKSK8LIFE** [comment]
why was this closed? @bar9

**Comment by bar9** [comment]
@DGKSK8LIFE I agree with you that documentation is important and needs to be improved in all places. I closed the issue because this something that will never be "done", especially with evolving software.
But please feel free to open more specific issues concerning documentation, in a granularity we will actually be able to check off, I'll do so myself in any case.

**Comment by DGKSK8LIFE** [comment]
Sounds good. Thanks @bar9
