### ISSUE TITLE
Opening Stories on a File / Moving Back to Gifs

### ISSUE THREAD

**Issue by henryboisdequin** [ide-stories/vscode-stories#62]
When a button shows up to replay the story and the window with the story is closed, it plays on a file that I'm working on, hence messing up my file. I think it would be best to switch to gifs again or we could have an option to create a gif or text one.

**Comment by benawad** [comment]
Try upgrading, just released something to try to fix that.

**Comment by henryboisdequin** [comment]
Yes, that fixes my problem, but still, a text file is a bit weird. I have to open it, and then discard it, I think a gif was much cleaner. Also, gifs will work better with all of the potiental features coming: comments, editing, descriptions, etc.

**Comment by benawad** [comment]
Yeah text recording might be too clunky

**Comment by breadnone** [comment]
@benawad The text recording has issues remembering it's last position, e.g: If my code is very long and I type it at the center, it wouldn't remember the last position when  it was recorded..

+1 for gif recording

**Comment by TheFern2** [comment]
I agree we need gifs as an alternative because they are a bit more interactive. And whoever can fight nsfw with gifs my hats off to them, you have imgur with probably a tons of devs and they have nsfw stuff all the time on front page.

Although I think for the text files we should be able to make it more interactive too.

- Autoscroll the file
- The file should be in a way that as soon as you click on something else it doesn't ask for saving, so maybe there is workspace file read-only? not sure just throwing ideas

**Comment by benawad** [comment]
I've decided to move back to gifs, I'm going to make a new branch for it

I'm going to include a report button + being able to follow people + we have GitHub auth so I'm hoping it'll be enough

**Comment by TheFern2** [comment]
Yeah following only some people should be enough, no more worrying about seeing front page porn from strangers.

Github auth is a nice extra layer too.

**Comment by bar9** [comment]
Let's continue this discussion under #73
